### ISSUE TITLE
New meeting time for Telecom User Group on 3rd Monday - APAC Time Zones

### ISSUE THREAD

**Issue by lixuna** [cncf/telecom-user-group#12]
Telecom User Group meeting time on 3rd Mondays - APAC Time Zones
---

The CNCF Telecom User Group meeting is currently held on the 1st and 3rd Mondays of the month at 8 AM PT. 

The group would like to reschedule the meetings on the 3rd Mondays of the month to be compatible with APAC Time Zones, starting on August 19th. The APAC Telecom User Group meeting will recur on a monthly basis on the 3rd Monday of the month. (The meetings on the 1st Mondays of the month will continue to be held at 8 AM PT.)

The proposed meeting time for Monday, August 19, 2019 is 7 - 8 PM Beijing Time (11 AM - 12 PM GMT).

Does this time work for folks in the Telecom User Group? 

Please vote in the comments.

**Comment by rannyh** [comment]
Would you consider scheduling it one hour later so it will be somewhat doable for US Pacific time zone? The proposed time is 4AM which will practically exclude west coast participants. 5AM will make it a bit more tolerable.

**Comment by hdamker** [comment]
Time works for me in general and would work on Monday, August 19. Could just imagine that it is too short term for a newly scheduled meeting already on next Monday.

**Comment by dankohn** [comment]
Good point. We'll plan to cancel the meeting on the 19th so the new date has more time to percolate.

**Comment by LiuyingCMRI** [comment]
7-8pm beijing time is more friendly for APAC paticipants. Thanks for the considerations !

**Comment by TamasZsiros** [comment]
Yes, works fine
