### ISSUE TITLE
[whitepaper][1.4]: CNF definition comments

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/telecom-user-group#44]
- I think we should back reference to the Virtual Network Function definition of ETSI NFV once we use a very similar acronym.
- I'm not sure what does it mean to facilitate a network functionality
- The text should clearly state that SG can be an example of a CNF

**Comment by jeffsaelens** [comment]
I thought that after much discussion, it was agreed upon that the definition of a CNF would not be dependent on legacy definitions as it is a completely novel approach to approaching the software in this space?

**Comment by dankohn** [comment]
I’m not sure I’d agree with “completely novel”, but we do have consensus to use a non-ETSI definition for CNFs. Further, we’re aiming to only have informative, not normative, references to external standards and other definitions.

**Comment by jeffsaelens** [comment]
"Completely novel" might have been too strongly worded; however, I still feel that the proposals in the paper are foreign from a telco waterfall, don't update it if it is not broken, perspective. 

Typically, we (operators) would buy very feature-rich boxes or VNFs. The VNF model looked similar to a PNF model from a consumption perspective, with additional NFVI and MANO considerations sprinkled on top. Cloud Native approaches, for both development and operations, are unique in that they expect immutability, a loosely coupled microservice architecture and a software-based deployment pipeline. This is a very different method of consumption from that of a VNF (which expects a different set of parameters).

While my choice of phrasing may have been a tad hyperbolic, I still believe that the end goal here is unique from the legacy way of handling VMs. As such, CNFs should have a fresh set of definitions not linked to ones presenting legacy approaches.

**Comment by ASalkever** [comment]
@CsatariGergely -  Feel free to open a PR  / Issue on this. You can definitely have a longer discussion about it in another white paper or a chapter in another white paper. For this one - which is a prologue - I'd like us to move forward with what we have  as per what @jeffsaelens is proposing. Thanks so much!

**Comment by taylor** [comment]
@CsatariGergely, if you have a specific suggested wording please create a PR.  Responding to the points that have not been addressed already.

> * I'm not sure what does it mean to facilitate a network functionality

By network functionality it's referring to the common networking definitions are standard before virtualization existed.  This is actually talking about capabilities on the network layers such as IP forwarding or packet inspection. 

> * The text should clearly state that SG can be an example of a CNF

By SG do you mean Serving Gateway and this sentence
> For example an Evolved Packet Core's (EPC) Serving Gateway could be implemented as a cloud native application and support all 3GPP requirements (eg. S1 protocol stack) allowing integration with other EPC services.

we could reword that to use CNF instead of cloud native application, though a CNF is a cloud native application.  Example update:

> For example an Evolved Packet Core's (EPC) Serving Gateway could be implemented as a CNF and support all 3GPP requirements (eg. S1 protocol stack) allowing integration with other EPC services.

cc @ASalkever

**Comment by CsatariGergely** [comment]
If it was agreed not to refer to ETSI NFV I accept that, so we can close this Issue without addressing this issue.
